### ISSUE TITLE
CMIP6.CMIP.SNU.SAM0-UNICON.historical.r1i1p1f1.day.tas.gn.v20190323  -- bad file name

### ISSUE THREAD

**Issue by martinjuckes** [cp4cds/cmip6_handle_checks#1]
http://hdl.handle.net/21.14100/8d2a767f-edcd-3cf9-a970-1d6e9ab5c696

https://handle-esgf.dkrz.de/lp/21.14100/a7dce4a7-0c0e-4f39-b791-be6acdee7d63

**Comment by wachsylon** [comment]
Hi Martin,
I informed Sungsu Park who is named in the files as contact but did not receive an answer up to now.
Best,
Fabi

**Comment by sjh11556** [comment]
The file (tas_day_SAM0-UNICON_historical_r1i1p1f1_gn3RaXbM42915.nc) is temporary file that was created during post-processing. The file is not part of the dataset and can be ignored. We republished the dataset (as CMIP6.CMIP.SNU.SAM0-UNICON.historical.r1i1p1f1.day.tas.gn.v20200916) without the corrupted file.

**Comment by martinjuckes** [comment]
@sjh11556 : thanks, I can see the new version in the handle registry at [8b114803-1cb7-3b7a-b806-7ce20d619dbb](https://handle-esgf.dkrz.de/lp/hdl:21.14100/8b114803-1cb7-3b7a-b806-7ce20d619dbb).
